version: '3.8'
services:
    web_server:
        image: nginx:latest
        container_name: rotab_cloud_web_server
        ports:
            - "9000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        networks:
            - rotab-network
    php:
        build: .
        container_name: rotab_php
        volumes:
            - ./src:/var/www/html
        networks:
            - rotab-network
    rotab_db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: YourPassWord4321
            MYSQL_DATABASE: ROTAB
            MYSQL_USER: root
        ports:
            - 9002:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - rotab-network
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
volumes:
  db_data:

networks:
  rotab-network:
    driver: bridge
